sudo: required
language: generic 
services:
  docker

before_install:
  - docker build -t shashankavunoori/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shashankavunoori/react-test npm test

after_success:
  - docker build -t shashankavunoori/multi-client ./client
  - docker build -t shashankavunoori/multi-nginx ./nginx
  - docker build -t shashankavunoori/multi-server ./server
  - docker build -t shashankavunoori/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push to docker hub
  - docker push shashankavunoori/multi-client
  - docker push shashankavunoori/multi-nginx
  - docker push shashankavunoori/multi-server
  - docker push shashankavunoori/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-202162575577'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
