sudo: required
language: generic 
services:
  docker

before_install:
  - docker build -t shashankavunoori/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shashankavunoori/react-test npm test

after_success:
  - docker build -t shashankavunoori/multi-client ./client
  - docker build -t shashankavunoori/multi-nginx ./nginx
  - docker build -t shashankavunoori/multi-server ./server
  - docker build -t shashankavunoori/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push shashankavunoori/multi-client
  - docker push shashankavunoori/multi-nginx
  - docker push shashankavunoori/multi-server
  - docker push shashankavunoori/multi-worker
